version: "3.8"

services:
  notification:
    build: .
    container_name: notification-service
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP_SERVERS: agile-kafka:9092
    networks:
      - shared-net

networks:
  shared-net:
    external: true
